FROM centos:latest
RUN yum isntall wget net-tools
RUN sudo yum install java-1.8.0-openjdk.x86_64
RUN sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
RUN sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum install jenkins
RUN echo "jenkins ALL=(ALL) NOPASSWD:ALL"" >> /etc/sudoers
RUN yum install git
RUN sudo systemctl start jenkins.service
RUN sudo systemctl enable jenkins.service
RUN sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp
RUN sudo firewall-cmd --reload
